### ISSUE TITLE
Implement dark mode

### ISSUE THREAD

**Issue by vavroom** [nicolas-steenhout/a11y-minute#3]
Sweet idea

**Comment by digilou** [comment]
[Added](https://github.com/nicolas-steenhout/a11y-minute/commit/9cad6a99df0f49f5db5002845b9598bbdbf25fe3) color scheme.

Checking how its working...

**Comment by digilou** [comment]
@vavroom Close if you approve of changes.

**Comment by vavroom** [comment]
I approooove :) Thank you
